# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches:
      - main
      - dev02

env:
  ARTIFACT: search_postfix_log-0.1.0-SNAPSHOT

permissions:
  contents: read
  checks: write
  pull-requests: write
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        PS1=x; source ~/.bashrc
        sbt test
    - name: Build installer
      run: |
        PS1=x; source ~/.bashrc
        sbt "Universal / packageBin"
        ln -s target/universal/$ARTIFACT.zip $ARTIFACT.zip
        cd target/universal
        sha256sum --binary $ARTIFACT.zip > ../../$ARTIFACT.zip.sha256
    - name: Upload to the internal storage
      run: |
        s3cmd --follow-symlinks put $ARTIFACT.zip s3://artifacts/
        s3cmd put $ARTIFACT.zip.sha256 s3://artifacts/
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: search_postfix_log
        path: |
          ${{ env.ARTIFACT }}.zip
          ${{ env.ARTIFACT }}.zip.sha256
        if-no-files-found: error
        compression-level: 0
        retention-days: 7
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if: always()
      with:
        files: |
          target/test-reports/*.xml

